### ISSUE TITLE
All Effects

### ISSUE THREAD

**Issue by Lorymi** [Sid-003/FaceApp.Net#3]
hi.
please add all effect (styles - filters)
(Makeup, Glasses, Wave, Beard , Etc ...)

**Comment by Sid-003** [comment]
I am not not sure if they even exist. I am aware that those filters exist in the actual FaceApp app, but couldn't really find the endpoints for it. I will look into it more when I have time.

**Comment by Sid-003** [comment]
Closing this issue as I have added all the effects.
