### ISSUE TITLE
no rate limit implemented, dont get blocked like i did

### ISSUE THREAD

**Issue by GIRU-GIRU** [Sid-003/FaceApp.Net#4]
https://www.npmjs.com/package/faceapp

according to this you can do 50 calls/10min, i must have gone over that as a ton of people were testing this in my discord server and now my requests get null'd. Would be cool if this project included a ratelimit - it's abit out of my depth to make one but i'm gonna have to try 

apart from that, great project and was really simple to setup for even a noob like me

**Comment by Niewiarowski** [comment]
It's a feature. Issue closed.

**Comment by Sid-003** [comment]
I am not really going to implement rate limit because the API isn't documented at all. I will update the README.md to make people aware of the rate limit. I have a cooldown on my bot, so I don't really have to be worried about getting blocked which other users can do as well. Thank you tho.

**Comment by GIRU-GIRU** [comment]
just for anyone who may stumble across here, i found this rate limiter for Discord bots in c#

https://github.com/Joe4evr/Discord.Addons/blob/master/src/Discord.Addons.Preconditions/Ratelimit/RatelimitAttribute.cs

need to be using the command module though. Sid, could i ask you what rate limit you are using (in terms of requests/time?

**Comment by Sid-003** [comment]
I use 1 request per 15 seconds per user. My bot isn't in many guilds, so it's fine for me. You might want to be more restrictive if your bot is in many guilds.
